// <auto-generated />
namespace FinkiCommunity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Anothermigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Anothermigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202001241655268_Another migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
